Traceback (most recent call last):
  File "src/gd.py", line 8, in <module>
    from archs import load_architecture
  File "/egr/research-slim/ghoshavr/edge-of-stability/src/archs.py", line 8, in <module>
    from data import num_classes, num_input_channels, image_size, num_pixels
  File "/egr/research-slim/ghoshavr/edge-of-stability/src/data.py", line 5, in <module>
    from cifar import load_cifar, load_mnist
  File "/egr/research-slim/ghoshavr/edge-of-stability/src/cifar.py", line 11, in <module>
    DATASETS_FOLDER = os.environ["DATASETS"]
  File "/egr/research-slim/ghoshavr/miniconda3/envs/lot/lib/python3.7/os.py", line 681, in __getitem__
    raise KeyError(key) from None
KeyError: 'DATASETS'
